name: Build and package for linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  LOVE_ARTIFACT_URL: "https://api.github.com/repos/love2d/love/actions/artifacts/4160426152/zip"

jobs:
  build:
    # should be as old as possible
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Build sqlite3
      run: |
        wget https://www.sqlite.org/2023/sqlite-amalgamation-3430100.zip
        7z x sqlite-amalgamation-3430100.zip
        mkdir lib
        gcc -shared -fPIC sqlite-amalgamation-3430100/sqlite3.c -o lib/libsqlite3.so

    - name: Create App image
      run: |
        # required for app image creation
        sudo apt install desktop-file-utils
        # create directory (git doesn't push empty directories)
        mkdir -p extra/linux/squashfs-root/share/games/oh-ce
        cp -r *.lua assets audio compat extlibs game game_handler server ui input_schemes extra/linux/squashfs-root/share/games/oh-ce
        # extract love over everything
        cd extra/linux
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "${{ env.LOVE_ARTIFACT_URL }}"
        7z x love12.zip
        chmod +x love-*.AppImage
        ./love-*.AppImage --appimage-extract
        # put libs in their place
        cp ../../lib/libsqlite3.so squashfs-root/lib
        # remove unneeded parts
        rm -r squashfs-root/share/applications/ squashfs-root/share/icons/ squashfs-root/share/lua squashfs-root/share/mime/ squashfs-root/share/pixmaps/ squashfs-root/love.desktop squashfs-root/love.svg
        # replace AppRun with custom one
        mv squashfs-root/AppRun_replace squashfs-root/AppRun
        # use appimagetool to create app image
        wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage squashfs-root oh-ce.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: oh-ce.AppImage
        path: extra/linux/oh-ce.AppImage
