name: Build and package for windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  LOVE_ARTIFACT_URL: "https://api.github.com/repos/love2d/love/actions/artifacts/4160439887/zip"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install dependencies
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          p7zip
          mingw-w64-x86_64-sqlite3
        update: true

    - uses: actions/checkout@v4.1.1

    - name: Create App bundle
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "${{ env.LOVE_ARTIFACT_URL }}"
        7z x love12.zip
        7z x love-*.zip
        mv love-*-win64 oh-ce
        mkdir oh-ce/lib
        cp /mingw64/bin/libsqlite3-0.dll oh-ce/lib/libsqlite3.dll
        cp /mingw64/bin/libwinpthread-1.dll oh-ce
        cp -r *.lua assets audio compat extlibs game game_handler server ui input_schemes oh-ce
        cp extra/windows/launch.bat oh-ce

        # create extra folder so the zip contains an oh-ce folder instead of directly having all files
        mkdir zip_contents
        mv oh-ce zip_contents

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: oh-ce
        path: zip_contents
